### ISSUE TITLE
Split rosbags2 by size

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#11]
## Description / Completion Criteria

"As a ROS2 user, I want my recorded rosbags to be split by size as they are recorded, so that I can incrementally transfer smaller files when dealing with large amounts of data" (also I need to be able to play these back)

* [x] `ros2 bag record` should take a new argument to specify the maximum individual bag file size
* [x] `ros2 bag play` should be able to play back these new bags
* [x] these new split bags should have an incremented bag version number'
* [ ] End to end testing

## Documents/Resources

* [ros2 bag play python API](https://github.com/ros2/rosbag2/blob/master/ros2bag/ros2bag/verb/play.py) parses the command line arguments and delegates to python bindings
* [Python bindings](https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/src/rosbag2_transport/rosbag2_transport_python.cpp#L94-L133) call the Player API
* [`Player` interface](https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/src/rosbag2_transport/player.hpp) uses the Reader API to read from bagfiles
* [`Reader` interface](https://github.com/ros2/rosbag2/blob/master/rosbag2/include/rosbag2/sequential_reader.hpp) interacts with the storage plugins
* [Sqlite3 storage plugin](https://github.com/ros2/rosbag2/blob/master/rosbag2_storage_default_plugins/include/rosbag2_storage_default_plugins/sqlite/sqlite_storage.hpp) where the underlying sqlite database is accessed from
