### ISSUE TITLE
[Tracking] Receive informative errors from TF issues

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#74]
This issue tracks an external problem that we want to address:

TF issues (dropped tf messages) do not give an informative error message. This makes it very difficult for a developer to debug what caused the problem.

A PR has already been opened for this, but the original author does not have the bandwidth to bring it up to the standard requested by OSRF. We will resume development from the point of that PR.

That original PR did 2 things
1. Translate MessageFilter FailureReason enums into a string, so they're easier to read than an integer failure reason (and make explicit that the error is coming from the MessageFilter)
2. Perform some more validation and return more error messages from the BufferCore when there are problems transforming

## External references
* Issue to solve https://github.com/ros2/geometry2/issues/118
* Original PR being rewritten here https://github.com/ros2/geometry2/pull/130

## To Do
* [x] Replace failureReason switch with function (1 above)
* [x] Unit test for failureReason string function (1 above)
* [ ] ^^ https://github.com/ros2/geometry2/pull/186
* [x] Update BufferCore messaging and validation
* [ ] ^ https://github.com/ros2/geometry2/pull/187/
